cursor #d8e4ea
cursor_text_color #bcc8ce

foreground            #d8e4ea
background            #0a1519
selection_foreground  #113348
selection_background  #abcae4
url_color             #46d6ff

color0   #0a1519
color1   #ff3377
color2   #46ff59
color3   #fff133
color4   #1fc3f2
color5   #005b76
color6   #46d6ff
color7   #e8f9ff
color8   #93a1a5
color9   #ff74a2
color10  #7dff8a
color11  #fff67d
color12  #61dcff
color13  #7de2ff
color14  #abecff
color15  #f5fcff
